// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJrmQCQSbLeCgkIbmFv1GAK_2Xt3yaq4',
    appId: '1:635269786028:web:a777bafd80edf104f17209',
    messagingSenderId: '635269786028',
    projectId: 'market3d-3844',
    authDomain: 'market3d-3844.firebaseapp.com',
    storageBucket: 'market3d-3844.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTK4q4SyGLO_0_zR-rd5psjDJb4bIlwGQ',
    appId: '1:635269786028:android:a54710715cf44e41f17209',
    messagingSenderId: '635269786028',
    projectId: 'market3d-3844',
    storageBucket: 'market3d-3844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZja_SL3uxJP6OZeLxImpsFkxPmBYqjI',
    appId: '1:635269786028:ios:593c38c4871497f0f17209',
    messagingSenderId: '635269786028',
    projectId: 'market3d-3844',
    storageBucket: 'market3d-3844.firebasestorage.app',
    iosBundleId: 'com.example.market3d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmZja_SL3uxJP6OZeLxImpsFkxPmBYqjI',
    appId: '1:635269786028:ios:593c38c4871497f0f17209',
    messagingSenderId: '635269786028',
    projectId: 'market3d-3844',
    storageBucket: 'market3d-3844.firebasestorage.app',
    iosBundleId: 'com.example.market3d',
  );
}
